SMAT-Inventory/Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using SMAT_Inventory.Models;
using SMAT_Inventory.Dapper;
using Dapper;
using SMAT_Inventory;
using System.Globalization;

using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Text;
using System.Reflection;
using OfficeOpenXml;
using System.Xml.Linq;
using static Org.BouncyCastle.Crypto.Engines.SM2Engine;

using System.Net.Http;
using Newtonsoft.Json.Linq;
using static QRCoder.PayloadGenerator;
using Microsoft.Ajax.Utilities;
using System.Security.Policy;
using OfficeOpenXml.Packaging.Ionic.Zlib;

namespace SMAT_Inventory.Controllers
{
    //[Authorize]
    public class AssetsController : Controller
    {
        
        public AssetsController()
        {
            if (GlobalVariables.AppUserId==0)
            {

            }

        }
        // GET: Assets
        public ActionResult Index()
        {
            return View();

        }
        public ActionResult test()
        {
            return View();

        }

        [AllowAnonymous]
        public ActionResult Login(LoginModel model)
        {
            //ViewBag.ReturnUrl = returnUrl;
            //GetWebSettings();
            //return View();
            GlobalVariables.AppUserId =0;
            GlobalVariables.AppUserName = "";
            GlobalVariables.AppUserEmail = "";
            GlobalVariables.remember_token = "";
            GlobalVariables.role = "";

            //User.Identity.IsAuthenticated
            //HttpCookie userSettingsCookieGet = Request.Cookies["SATUserSettings"];

            LoginViewModel mode = new LoginViewModel();
            if (model.logintype == "stafflogin")
            {
                using (DAPPER_DATA_SERVICESMA dapper = new DAPPER_DATA_SERVICESMA())
                {
                    //LoginViewModel model = new LoginViewModel();
                    //UserName = "Zeesshan";
                    //Password = "123";
                    dapper.AddUnicodeStringParameter("UserName", model.Email, 50);
                    dapper.AddUnicodeStringParameter("Password", model.Password, 40);

                    var result = dapper.query_multiple("dbo.UserAuth");
                    if (result.hasRows() && model.Email != null)
                    {
                        mode.LoginModel = result.Read<LoginModel>().FirstOrDefault();
                        mode.SetModel();
                        if (mode.LoginModel != null)
                        {
                            GlobalVariables.AppUserId = mode.LoginModel.id;
                            GlobalVariables.AppUserName = mode.LoginModel.Name;
                            GlobalVariables.AppUserEmail = mode.LoginModel.Email;
                            GlobalVariables.remember_token = mode.LoginModel.remember_token;
                            GlobalVariables.role = mode.LoginModel.role;
                            GlobalVariables.AppUserPassword = model.Password;
                            GlobalVariables.logintype = model.logintype;

                            GetWebSettings();
                            GetUserPermissions();
                            return RedirectToAction("Dashboard", "Home");
                        }
                        else
                        {
                            ViewBag.ErrorMessage = "Invalid username or password.";
                            return View("Login");
                        }

                    }
                    else
                    {
                        //ViewBag.ErrorMessage = "Invalid username or password.";
                        return View("Login");
                    }
                } 
            }
            else
            {
                using (DAPPER_DATA_SERVICE dapper = new DAPPER_DATA_SERVICE())
                {
                    //LoginViewModel model = new LoginViewModel();
                    //UserName = "Zeesshan";
                    //Password = "123";
                    dapper.AddUnicodeStringParameter("UserName", model.Email, 50);
                    dapper.AddUnicodeStringParameter("Password", model.Password, 40);

                    var result = dapper.query_multiple("dbo.UserAuth");
                    if (result.hasRows() && model.Email != null)
                    {
                        mode.LoginModel = result.Read<LoginModel>().FirstOrDefault();
                        mode.SetModel();
                        if (mode.LoginModel != null)
                        {
                            GlobalVariables.AppUserId = mode.LoginModel.id;
                            GlobalVariables.AppUserName = mode.LoginModel.Name;
                            GlobalVariables.AppUserEmail = mode.LoginModel.Email;
                            GlobalVariables.remember_token = mode.LoginModel.remember_token;
                            GlobalVariables.role = mode.LoginModel.role;
                            GlobalVariables.AppUserPassword = model.Password;
                            GlobalVariables.logintype = model.logintype;
                            GlobalVariables.AssetTransfer_AddReviewer = mode.LoginModel.AssetTransfer_AddReviewer;
                            GlobalVariables.AssetTransfer_Approver = mode.LoginModel.AssetTransfer_Approver;
                            GlobalVariables.AssetTransfer_Receiver = mode.LoginModel.AssetTransfer_Receiver;

                            GetWebSettings();
                            GetUserPermissions();
                            return RedirectToAction("Dashboard", "Home");
                        }
                        else
                        {
                            ViewBag.ErrorMessage = "Invalid username or password.";
                            return View();
                        }

                    }
                    else
                    {
                        //ViewBag.ErrorMessage = "Invalid username or password.";
                        return View();
                    }
                }
            }

        }
        /*
        public ActionResult stafflogin(LoginModel model)
        {
            //ViewBag.ReturnUrl = returnUrl;
            //GetWebSettings();
            //return View();

            LoginViewModel mode = new LoginViewModel();

            using (DAPPER_DATA_SERVICESMA dapper = new DAPPER_DATA_SERVICESMA())
            {
                //LoginViewModel model = new LoginViewModel();
                //UserName = "Zeesshan";
                //Password = "123";
                dapper.AddUnicodeStringParameter("UserName", model.Email, 50);
                dapper.AddUnicodeStringParameter("Password", model.Password, 40);

                var result = dapper.query_multiple("dbo.UserAuth");
                if (result.hasRows() && model.Email != null)
                {
                    mode.LoginList = result.Read<LoginModel>().ToList();
                    mode.SetModel();
                    if (mode.TotalCount > 0)
                    {
                        GlobalVariables.AppUserId = mode.LoginModel.id;
                        GlobalVariables.AppUserName = mode.LoginModel.Name;
                        GlobalVariables.AppUserEmail = mode.LoginModel.Email;
                        GlobalVariables.remember_token = mode.LoginModel.remember_token;
                        GlobalVariables.role = mode.LoginModel.role;
                        GlobalVariables.AppUserPassword = model.Password;

                        GetWebSettings();
                        GetUserPermissions();
                        return RedirectToAction("Dashboard", "Home");
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Invalid username or password.";
                        return View("Login");
                    }

                }
                else
                {
                    //ViewBag.ErrorMessage = "Invalid username or password.";
                    return View("Login");
                }
            }

        }
            */
        private void GetWebSettings()
        {
            using (DAPPER_DATA_SERVICE dapper = new DAPPER_DATA_SERVICE())
            {
                try
                {
                    GlobalVariables.GetWebSettingValue.Clear();
                    List<WebSetting> WebSetting = new List<WebSetting>();
                    WebSetting = dapper.execute_stored_procedure<WebSetting>("dbo.GetWebSetting");

                    GlobalVariables.GetWebSettingValue.AddRange(WebSetting);
                }
                catch (Exception ex)
                {
                    //sysExceptions.logException(ex.Message, ex.StackTrace);
                }
            }
        }
        private void GetUserPermissions()
        {
            if (GlobalVariables.logintype == "stafflogin")
            {
                using (DAPPER_DATA_SERVICESMA dapperm = new DAPPER_DATA_SERVICESMA())
                {
                    try
                    {
                        GlobalVariables.GetUserPermissionsValue.Clear();
                        List<userpermissions> userpermissions = new List<userpermissions>();
                        dapperm.AddIntegerParameter("id", GlobalVariables.AppUserId);
                        userpermissions = dapperm.execute_stored_procedure<userpermissions>("dbo.UserPermissions");

                        GlobalVariables.GetUserPermissionsValue.AddRange(userpermissions);
                    }
                    catch (Exception ex)
                    {
                        //sysExceptions.logException(ex.Message, ex.StackTrace);
                    }
                }
            }
            else

SMAT-Inventory/Views/Assets/grouprestore.cshtml
@model SMAT_Inventory.Models.groupViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <div class="card mini-stats-wid">
            <div class="card-body">
                <div class="d-flex">
                    <div class="flex-grow-1">
                        <p class="text-muted fw-medium">Zones</p>
                        <h4 class="mb-0">@Model.zonecount</h4>
                    </div>

                    <div class="flex-shrink-0 align-self-center">
                        <div class="mini-stat-icon avatar-sm rounded-circle bg-primary">
                            <span class="avatar-title">
                                <i class="bx bx-copy-alt font-size-24"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card mini-stats-wid">
            <div class="card-body">
                <div class="d-flex">
                    <div class="flex-grow-1">
                        <p class="text-muted fw-medium">Branches</p>
                        <h4 class="mb-0">@Model.branchcount</h4>
                    </div>

                    <div class="flex-shrink-0 align-self-center ">
                        <div class="avatar-sm rounded-circle bg-primary mini-stat-icon">
                            <span class="avatar-title rounded-circle bg-primary">
                                <i class="bx bx-archive-in font-size-24"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card mini-stats-wid">
            <div class="card-body">
                <div class="d-flex">
                    <div class="flex-grow-1">
                        <p class="text-muted fw-medium">Groups</p>
                        <h4 class="mb-0">@Model.groupcount</h4>
                    </div>

                    <div class="flex-shrink-0 align-self-center ">
                        <div class="avatar-sm rounded-circle bg-primary mini-stat-icon">
                            <span class="avatar-title rounded-circle bg-primary">
                                <i class="bx bx-archive-in font-size-24"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 message"></div>
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Branch List</h4>
                <table id="groups-datatable" class="table table-bordered dt-responsive nowrap w-100">
                    <div class="row">
                        <div class="card mini-stats-wid">
                            <div class="d-flex">
                                <div class="flex-grow-1">
                                    <div class="pagination">
                                        @{
                                            var pageCount = Math.Ceiling((double)Model.TotalCount / Model.PageSize);
                                        }

                                        @for (var i = 1; i <= pageCount; i++)
                                        {
                                            <a class="btn @(i == Model.CurrentPage ? "btn-primary" : "btn-secondary")" href="@Url.Action("/grouplist", new { page = i, pageSize = Model.PageSize })">@i</a>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <thead>
                        <tr>
                            <th>
                                <a href="@Url.Action("/grouplist", new { page = Model.CurrentPage, pageSize = Model.PageSize, sortColumn = "id", sortOrder = Model.SortColumn == "id" && Model.SortOrder == "asc" ? "desc" : "asc" })">
                                    ID @(Model.SortColumn == "id" ? (Model.SortOrder == "asc" ? "▲" : "▼") : "")
                                </a>
                            </th>
                            <th>
                                <a href="@Url.Action("/grouplist", new { page = Model.CurrentPage, pageSize = Model.PageSize, sortColumn = "name", sortOrder = Model.SortColumn == "name" && Model.SortOrder == "asc" ? "desc" : "asc" })">
                                    Group Name @(Model.SortColumn == "name" ? (Model.SortOrder == "asc" ? "▲" : "▼") : "")
                                </a>
                            </th>
                            <th>
                                <a href="@Url.Action("/grouplist", new { page = Model.CurrentPage, pageSize = Model.PageSize, sortColumn = "person_name", sortOrder = Model.SortColumn == "person_name" && Model.SortOrder == "asc" ? "desc" : "asc" })">
                                    Person Name @(Model.SortColumn == "person_name" ? (Model.SortOrder == "asc" ? "▲" : "▼") : "")
                                </a>
                            </th>
                            <th>
                                <a href="@Url.Action("/grouplist", new { page = Model.CurrentPage, pageSize = Model.PageSize, sortColumn = "person_Designation", sortOrder = Model.SortColumn == "person_Designation" && Model.SortOrder == "asc" ? "desc" : "asc" })">
                                    Person Designation @(Model.SortColumn == "person_Designation" ? (Model.SortOrder == "asc" ? "▲" : "▼") : "")
                                </a>
                            </th>
                            <th>
                                <a href="@Url.Action("/grouplist", new { page = Model.CurrentPage, pageSize = Model.PageSize, sortColumn = "BranchesinGroup", sortOrder = Model.SortColumn == "BranchesinGroup" && Model.SortOrder == "asc" ? "desc" : "asc" })">
                                    Branches @(Model.SortColumn == "BranchesinGroup" ? (Model.SortOrder == "asc" ? "▲" : "▼") : "")
                                </a>
                            </th>

                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var group in Model.grouplist)
                        {
                            <tr>
                                <td>@group.id</td>
                                <td>@group.name</td>
                                <td>@group.person_name</td>
                                <td>@group.person_designation</td>
                                <td><a href="#" class="btn btn-warning view-branches" data-id="@group.id">@group.BranchesinGroup</a></td>
                                <td>
                                    <a href="javascript::void()" class="btn btn-success restore-group" data-id="@group.id"><i class="bx bx-archive-out"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="pagination">
                    @{
                        var pageCountd = Math.Ceiling((double)Model.TotalCount / Model.PageSize);
                    }

                    @for (var i = 1; i <= pageCountd; i++)
                    {
                        <a class="btn @(i == Model.CurrentPage ? "btn-primary" : "btn-secondary")" href="@Url.Action("/grouplist", new { page = i, pageSize = Model.PageSize })">@i</a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $(document).on("click", ".restore-group", function(event) {
            event.preventDefault(); // Prevent default action
            if (confirm('Do want to Restore Group?')) {
                var id = $(this).data('id');
                $.ajax({
                    url: '@Url.Action("grouprestorenow", "Assets")',
                    type: 'POST',
                    data: { id: id },
                    success: function(response) {
                        $('.message').html('<div class="alert alert-' + response.type + ' alert-dismissible fade show" role="alert"><i class="mdi ' + response.icon + ' me-2"></i>' + response.message + '<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>');
                        window.location.reload();
                    },
                    error: function(error) {
                        console.log(error);
                    }
                });
            }
        });
    });
</script>

SMAT-Inventory/Views/Assets/messagelist.cshtml
@model SMAT_Inventory.Models.messagesViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-md-4">
        <div class="card mini-stats-wid">
            <div class="card-body">
                <div class="d-flex">
                    <div class="flex-grow-1">
                        <p class="text-muted fw-medium">Message List</p>
                        <h4 class="mb-0" id="zones_count">@Model.TotalCount</h4>
                    </div>

                    <div class="flex-shrink-0 align-self-center">
                        <div class="avatar-sm rounded-circle bg-primary mini-stat-icon">
                            <span class="avatar-title rounded-circle bg-primary">
                                <i class="bx bx-purchase-tag-alt font-size-24"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<table class="table table-bordered dt-responsive nowrap w-100">
    <div class="row">
        <div class="card mini-stats-wid">
            <div class="d-flex">
                <div class="flex-grow-1">
                    <div class="pagination">
                        @{
                            var pageCount = Math.Ceiling((double)Model.TotalCount / Model.PageSize);
                        }

                        @for (var i = 1; i <= pageCount; i++)
                        {
                            <a class="btn @(i == Model.CurrentPage ? "btn-primary" : "btn-secondary")" href="@Url.Action("/messagelist", new { page = i, pageSize = Model.PageSize })">@i</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <thead>
        <tr>
            <th>
                <a href="@Url.Action("/messagelist", new { page = Model.CurrentPage, pageSize = Model.PageSize, sortColumn = "Id", sortOrder = Model.SortColumn == "Id" && Model.SortOrder == "asc" ? "desc" : "asc" })">
                    ID @(Model.SortColumn == "Id" ? (Model.SortOrder == "asc" ? "▲" : "▼") : "")
                </a>
            </th>
            <th>
                <a href="@Url.Action("/messagelist", new { page = Model.CurrentPage, pageSize = Model.PageSize, sortColumn = "subject", sortOrder = Model.SortColumn == "subject" && Model.SortOrder == "asc" ? "desc" : "asc" })">
                    Subject @(Model.SortColumn == "subject" ? (Model.SortOrder == "asc" ? "▲" : "▼") : "")
                </a>
            </th>
            <th>
                <a href="@Url.Action("/messagelist", new { page = Model.CurrentPage, pageSize = Model.PageSize, sortColumn = "startdate", sortOrder = Model.SortColumn == "startdate" && Model.SortOrder == "asc" ? "desc" : "asc" })">
                    Start Date @(Model.SortColumn == "startdate" ? (Model.SortOrder == "asc" ? "▲" : "▼") : "")
                </a>
            </th>
            <th>
                <a href="@Url.Action("/messagelist", new { page = Model.CurrentPage, pageSize = Model.PageSize, sortColumn = "enddate", sortOrder = Model.SortColumn == "enddate" && Model.SortOrder == "asc" ? "desc" : "asc" })">
                    End Date @(Model.SortColumn == "enddate" ? (Model.SortOrder == "asc" ? "▲" : "▼") : "")
                </a>
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var message in Model.messagelist)
        {
            <tr>
                <td>@message.id</td>
                <td>@message.subject</td>
                <td>@message.startdate</td>
                <td>@message.enddate</td>

                <td>

                    <div class="dropdown">
                        <a href="#" class="dropdown-toggle btn btn-primary" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="mdi mdi-dots-horizontal font-size-18"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" style="">
                            <li><a href="@Url.Action("messageview", "Assets", new { id = message.id })" target="_blank" class="dropdown-item btn btn btn-success" data-id="1"><i class="mdi mdi-pencil font-size-16 text-danger me-1"></i> View Message</a></li>
                            <li><a href="@Url.Action("messageadd", "Assets", new { id = message.id })" class="dropdown-item btn btn btn-success" data-id="1"><i class="mdi mdi-pencil font-size-16 text-danger me-1"></i> Edit Message</a></li>
                            <li><a class="dropdown-item btn btn-danger disable-zone" data-id="@message.id"><i class="mdi mdi-trash-can-outline font-size-16 text-danger me-1"></i> Delete Message</a></li>
                        </ul>
                    </div>
                    @*@<button class="btn btn-sm btn-danger disable-zone" data-id="@zone.id">Disable</button>
            <button class="btn btn-sm btn-info zone-branches" data-zone="@zone.id">View Branches</button>
                    *@
                </td>
            </tr>
        }
    </tbody>
</table>


<div class="pagination">
    @{
        var pageCountd = Math.Ceiling((double)Model.TotalCount / Model.PageSize);
    }

    @for (var i = 1; i <= pageCountd; i++)
    {
        <a class="btn @(i == Model.CurrentPage ? "btn-primary" : "btn-secondary")" href="@Url.Action("/messagelist", new { page = i, pageSize = Model.PageSize })">@i</a>
    }
</div>




<!-- Modal -->
<div class="modal fade" id="branchModal" tabindex="-1" role="dialog" aria-labelledby="branchModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="branchModalLabel">Branch List</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Table to display branch list -->
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Branch code</th>
                            <th scope="col">Branch Name</th>
                        </tr>
                    </thead>
                    <tbody id="branchList">
                        <!-- Dynamic content will go here -->
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $(document).on("click", ".disable-zone", function(event) {
            event.preventDefault(); // Prevent default action
            if (confirm('Do you want to remove this message?')) {
                var id = $(this).data('id');
                $.ajax({
                    url: '@Url.Action("messagedelete", "Assets")',
                    type: 'POST',
                    data: { id: id },
                    success: function(response) {
                        $('.message').html('<div class="alert alert-' + response.type + ' alert-dismissible fade show" role="alert"><i class="mdi ' + response.icon + ' me-2"></i>' + response.message + '<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>');
                        window.location.reload();
                    },
                    error: function(error) {
                        console.log(error);
                    }
                });
            }
        });
    });
</script>
<script>
    $('.zone-branches').on('click', function () {
        var Id = $(this).data('zone'); // Get the zone id from the label

        // Clear previous data in the modal
        //$('#branchList').empty();

        // AJAX request to fetch branches for the selected zone
        $.ajax({
            url: '/Assets/MessageSingleGet', // Replace with your server-side URL
            type: 'GET',
            data: { Id: Id },
            success: function (branches) {
                // branches should be an array of branch objects { branchId, branchName }
                branches.forEach(function (branch) {
                    $('#branchList').append('<tr><td>' + branch.code + '</td><td>' + branch.name + '</td></tr>');
                });

                // Show the modal
                $('#branchModal').modal('show');
            },
            error: function () {
                alert('Error fetching branch data');
            }
        });
    });

</script>

SMAT-Inventory/Views/Assets/staffuserChangePassword.cshtml
@*@model SMAT_Inventory.Models.UserViewModel*@

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0 font-size-18">Change password : @GlobalVariables.AppUserName (@GlobalVariables.AppUserEmail)</h4>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <form name="add-branch-form" action="" method="post" enctype="multipart/form-data">


                    <div class="col-md-3">
                        <div class="mb-3">
                            <label for="password-input" class="form-label">Current password</label>
                            <div class="input-group auth-pass-inputgroup">
                                <input type="password" class="form-control" name="currentPassword" id="currentPassword" value="" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-3">
                            <label for="password-input" class="form-label">Enter New Password</label>
                            <div class="input-group auth-pass-inputgroup">
                                <input type="password" class="form-control" name="NewPassword" id="NewPassword" required>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="mb-3">
                            <label for="cpassword-input" class="form-label">Enter Confirm Password</label>
                            <input type="password" class="form-control" name="ConfirmPassword" id="ConfirmPassword" required>
                        </div>
                    </div>
                    <div>
                        <button type="button" class="btn btn-primary w-md" id="btnSave">Change Password</button>
                    </div>
                </form>

                <x-error-messages-section></x-error-messages-section>


            </div>
            <!-- end card body -->
        </div>
        <!-- end card -->
    </div>
    <!-- end col -->
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
     $(document).ready(function () {

         $('#btnSave').on('click', function () {
             var currentPassword = $('#currentPassword').val();
             var NewPassword = $('#NewPassword').val();
             var ConfirmPassword = $('#ConfirmPassword').val();
             var id = @GlobalVariables.AppUserId;

             //alert(vali);
             if ('@GlobalVariables.AppUserPassword' != currentPassword) {
                 alert("Invalid Current Password");
                 return;
             }
             if (NewPassword != ConfirmPassword) {
                 alert("New password and Confirm Password are not Same");
                 return;
             }

             //var Fn = { id: id, NewPassword: NewPassword };

             $.ajax({
                 contentType: 'application/json',
                 type: "POST",
                 url: "/Assets/usersavecchangepassword",
                 dataType: "json",
                 data: JSON.stringify({ id: id, NewPassword: NewPassword }),
                 async: false,
                 success: function (data) {
                     if (data.success) {
                         alert(data.message);
                         window.location.href = '@Url.Action("Login", "Assets")';
                         window.location.reload(true);
                     }
                     else {
                         alert("Error: " + data.message)
                     }
                 }

             });


         });
     });
</script>